# A. Extract

In [ ]:
'''
Syntax dibawah ini untuk mengimport pandas dengan alias pd, mengimport package webdriver 
untuk mengaktifkan syntax drive, mengimport Beautifulsoup untuk mengaktifkan syntax soup, 
dan time untuk mengaktifkan syntax time.sleep().
'''
import pandas as pd
from selenium import webdriver
from bs4 import BeautifulSoup
import time

'''
Syntax di bawah untuk membuat list kosong yang berguna untuk menampung data yang akan diambil.
'''
name = []
price = []
stock_availability = []
price_discount = []
'''
Syntax di bawah untuk membuka browser Google Chrome dengan menggunakan webdriver.
'''
driver = webdriver.Chrome()

'''
Syntax dibawah menunjukan penggunaan for in untuk melakukan iterasi berupa membuka browser Google Chrome dengan url yang dituju 
dengan arti range yaitu mengambil data dari halaman 1 sampai halaman 2 dengan setiap halamannya dilakukan jeda selama 7 detik 
untuk memastikan bahwa data yang ada di halaman tersebut sudah terbuka semua.
'''
for page in range(1,3):
    url = f'https://www.sweelee.co.id/en/collections/gitar-elektrik?page={page}&sortBy=sweelee-id_products_recently_ordered_count_desc' # Ini url

    driver.get(url) 
    time.sleep(7)
    html = driver.page_source # ini untuk menyimpan sumber halaman web yang sudah dibuka ke dalam variabel html.
    '''
    Syntax dibawah, BeautifulSoup untuk mengambil sumber halaman web yang 
    sudah disimpan dalam variabel html diatas, dengan menggunakan syntax 'html.parser'.
    Setelah itu dimasukan ke dalam variabel soup untuk pengambilan data selanjutnya.
    '''
    soup = BeautifulSoup(html, 'html.parser') 
    
    '''
    Syntax dibawah menunjukan analogi box yang diambil dari setiap komponen barang 
    yang akan diambil datanya.
    Dengan keterangan bahwa find_all untuk mencari semua data yang sesuai dengan kriteria.
    Kriteria yang dimasukan yaitu dengan warna yang terkandung dengan dilihat melalui inspect element 
    pada browser dengan cara klik kanan, lalu klik inspect.
    Contoh: boxes = soup.find_all('biru_tua',{'biru muda':'oren'})
    '''

    boxes = soup.find_all('div',{'data-card-meta-alignment':'flex-start'}) 

    for box in boxes: # penggunaan for in untuk melakukan iterasi berupa memasukan data yang akan di cari melalui find melalui syntax selanjutnya.
        # Syntax dibawah untuk pencarian data ke dalam variabel el_name, el_price, el_stock, el_price_discount untuk setiap data yang sudah di cari.
        el_name = box.find('h5',{'class':'product-card__title product-card__title-regular'})

        el_price = box.find('div',{'class':'product-card__price product-card__price-bold product-card__price-regular-desktop product-card__price-regular-mobile'})

        el_stock = box.find('div',{'class':'product-card__stock'})

        el_price_discount = box.find('span',{'class':'text-small'})

        try:
            name.append(el_name.get_text()) # syntax untuk mengambil text yang berbeda dari data yang sudah dimasukan ke dalam el_name, dan dimasukan ke dalam list kosong bernama name.
        except:
            name.append(None) # syntax untuk memberikan nilai None jika data yang dicari tidak ditemukan, dan dimasukan ke dalam list kosong bernama name.
            # syntax di bawah dst juga pengerjaannya sama dengan penjelasan try dan except di atas.
        try:
            price.append(el_price.get_text())
        except:
            price.append(None)

        try:
            stock_availability.append(el_stock.get_text())
        except:
            stock_availability.append(None)

        try:
            price_discount.append(el_price_discount.get_text())
        except:
            price_discount.append(None)


driver.quit() # syntax untuk menutup browser yang sudah dibuka setelah proses pengambilan data selesai.

df = pd.DataFrame() # syntax untuk membuat dataframe kosong dengan menggunakan pandas, dan dimasukan ke dalam variabel df.
df['nama_produk'] = name # syntax untuk membuat kolom baru dengan nama 'nama_produk' ke dalam dataframe df, dan mengisi kolom tersebut dengan data yang sudah diambil dan disimpan dalam list name.
df['harga_original'] = price # syntax yang sama dengan pengerjaan di atas, begitupun syntax di bawahnya.
df['harga_diskon'] = price_discount
df['ketersediaan_stock'] = stock_availability

In [ ]:
# Syntax di bawah untuk mengecek isi dari DataFrame hasil scrapping.
df

,nama_produk,harga_original,harga_diskon,ketersediaan_stock
0,Squier FSR Sonic Stratocaster HSS Electric G...,Rp 3.950.000,None,In Stock
1,Heritage Ascent Collection H-150 Electric Gu...,Rp 4.000.000,None,In Stock
2,Ibanez Gio GRG120QASP-BKG 6-String Electric ...,Rp 4.370.000,None,In Stock
3,Squier Sonic Telecaster Electric Guitar w/Bl...,Rp 3.160.000,Rp 3.950.000,In Stock
4,Fender American Vintage II 1966 Jazzmaster E...,Rp 54.600.000,None,Low in Stock
...,...,...,...,...
123,Heritage Ascent Collection H-150 Electric Gu...,Rp 4.000.000,None,In Stock
124,Heritage Standard H-535 Semi-Hollow Electric...,Rp 46.250.000,None,In Stock
125,Heritage Ascent Collection H-150 Electric Gu...,Rp 4.000.000,None,In Stock
126,Harmony Standard Series Jupiter Electric Gui...,Rp 23.000.000,None,In Stock
127,Heritage Standard H-535 Semi-Hollow Electric...,Rp 46.250.000,None,In Stock

In [ ]:
df.info()
'''
Diketahui bahwa data di bawah ini berbentuk DataFrame, yang memiliki 4 column dan 128 rows. 
Keseluruhan column memiliki type data string. Keseluruhan column tidak memiliki null value
terkecuali column harga_diskon. Total size data tersebut yaitu 4.1+ KB.
'''

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   nama_produk         128 non-null    object
 1   harga_original      128 non-null    object
 2   harga_diskon        12 non-null     object
 3   ketersediaan_stock  128 non-null    object
dtypes: object(4)
memory usage: 4.1+ KB

In [ ]:
# Syntax di bawah untuk menyimpan hasil scrapping ke dalam file CSV. Arti index=False adalah tidak menyertakan column index pada file CSV yang disimpan.
df.to_csv('P0M1_Data_Kotor.csv', index=False)

# B. Transform

In [ ]:
# syntax loading data
df = pd.read_csv('P0M1_Data_Kotor.csv')

In [78]:
df

,nama_produk,harga_original,harga_diskon,ketersediaan_stock
0,Squier FSR Sonic Stratocaster HSS Electric G...,Rp 3.950.000,NaN,In Stock
1,Heritage Ascent Collection H-150 Electric Gu...,Rp 4.000.000,NaN,In Stock
2,Ibanez Gio GRG120QASP-BKG 6-String Electric ...,Rp 4.370.000,NaN,In Stock
3,Squier Sonic Telecaster Electric Guitar w/Bl...,Rp 3.160.000,Rp 3.950.000,In Stock
4,Fender American Vintage II 1966 Jazzmaster E...,Rp 54.600.000,NaN,Low in Stock
...,...,...,...,...
123,Heritage Ascent Collection H-150 Electric Gu...,Rp 4.000.000,NaN,In Stock
124,Heritage Standard H-535 Semi-Hollow Electric...,Rp 46.250.000,NaN,In Stock
125,Heritage Ascent Collection H-150 Electric Gu...,Rp 4.000.000,NaN,In Stock
126,Harmony Standard Series Jupiter Electric Gui...,Rp 23.000.000,NaN,In Stock
127,Heritage Standard H-535 Semi-Hollow Electric...,Rp 46.250.000,NaN,In Stock

## Cleaning data

In [79]:
'''
Syntax di bawah ini untuk mengubah data di column 'harga_original' berupa menghilangkan
kata 'Rp' dan '.' menjadi hilang/kosong dan mengubah type data di column tersebut 
menjadi integer/Int64.
'''
df['harga_original'] = df['harga_original'].str.replace('Rp', ' ')
df['harga_original'] = df['harga_original'].str.replace('.', '')
df['harga_original'] = df['harga_original'].astype('Int64')

In [80]:
df

,nama_produk,harga_original,harga_diskon,ketersediaan_stock
0,Squier FSR Sonic Stratocaster HSS Electric G...,3950000,NaN,In Stock
1,Heritage Ascent Collection H-150 Electric Gu...,4000000,NaN,In Stock
2,Ibanez Gio GRG120QASP-BKG 6-String Electric ...,4370000,NaN,In Stock
3,Squier Sonic Telecaster Electric Guitar w/Bl...,3160000,Rp 3.950.000,In Stock
4,Fender American Vintage II 1966 Jazzmaster E...,54600000,NaN,Low in Stock
...,...,...,...,...
123,Heritage Ascent Collection H-150 Electric Gu...,4000000,NaN,In Stock
124,Heritage Standard H-535 Semi-Hollow Electric...,46250000,NaN,In Stock
125,Heritage Ascent Collection H-150 Electric Gu...,4000000,NaN,In Stock
126,Harmony Standard Series Jupiter Electric Gui...,23000000,NaN,In Stock
127,Heritage Standard H-535 Semi-Hollow Electric...,46250000,NaN,In Stock

In [81]:
'''
Syntax di bawah ini untuk mengubah data di column 'harga_diskon' berupa menghilangkan
kata 'Rp' dan '.' menjadi hilang/kosong dan mengubah type data di column tersebut 
menjadi integer/Int64.
'''
df['harga_diskon'] = df['harga_diskon'].str.replace('Rp', ' ')
df['harga_diskon'] = df['harga_diskon'].str.replace('.', '')
df['harga_diskon'] = df['harga_diskon'].astype('Int64')

In [82]:
df

,nama_produk,harga_original,harga_diskon,ketersediaan_stock
0,Squier FSR Sonic Stratocaster HSS Electric G...,3950000,<NA>,In Stock
1,Heritage Ascent Collection H-150 Electric Gu...,4000000,<NA>,In Stock
2,Ibanez Gio GRG120QASP-BKG 6-String Electric ...,4370000,<NA>,In Stock
3,Squier Sonic Telecaster Electric Guitar w/Bl...,3160000,3950000,In Stock
4,Fender American Vintage II 1966 Jazzmaster E...,54600000,<NA>,Low in Stock
...,...,...,...,...
123,Heritage Ascent Collection H-150 Electric Gu...,4000000,<NA>,In Stock
124,Heritage Standard H-535 Semi-Hollow Electric...,46250000,<NA>,In Stock
125,Heritage Ascent Collection H-150 Electric Gu...,4000000,<NA>,In Stock
126,Harmony Standard Series Jupiter Electric Gui...,23000000,<NA>,In Stock
127,Heritage Standard H-535 Semi-Hollow Electric...,46250000,<NA>,In Stock

In [ ]:
# Syntax untuk mengetahui struktur data setelah perubahan type pada 2 column di atas.
df.info()
'''
Diketahui bahwa data tersebut berbentuk DataFrame dan memiliki 4 column dan 128 rows. 
Untuk column nama_produk dan ketersediaan_stock memiliki type data string, untuk data column yang sudah 
diubah typenya yaitu harga_original dan harga_diskon menjadi type data integer/Int64. Keseluruhan column tidak memiliki null value
terkecuali column harga_diskon. Total size data tersebut yaitu 4.4+ KB.
'''

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   nama_produk         128 non-null    object
 1   harga_original      128 non-null    Int64
 2   harga_diskon        12 non-null     Int64
 3   ketersediaan_stock  128 non-null    object
dtypes: Int64(2), object(2)
memory usage: 4.4+ KB

In [ ]:
# Merubah nama column harga_original menjadi harga, dan harga_diskon menjadi harga_tidak_diskon.
df = df.rename(columns={'harga_original' : 'harga', 'harga_diskon' : 'harga_tidak_diskon'})

In [84]:
df

,nama_produk,harga,harga_tidak_diskon,ketersediaan_stock
0,Squier FSR Sonic Stratocaster HSS Electric G...,3950000,<NA>,In Stock
1,Heritage Ascent Collection H-150 Electric Gu...,4000000,<NA>,In Stock
2,Ibanez Gio GRG120QASP-BKG 6-String Electric ...,4370000,<NA>,In Stock
3,Squier Sonic Telecaster Electric Guitar w/Bl...,3160000,3950000,In Stock
4,Fender American Vintage II 1966 Jazzmaster E...,54600000,<NA>,Low in Stock
...,...,...,...,...
123,Heritage Ascent Collection H-150 Electric Gu...,4000000,<NA>,In Stock
124,Heritage Standard H-535 Semi-Hollow Electric...,46250000,<NA>,In Stock
125,Heritage Ascent Collection H-150 Electric Gu...,4000000,<NA>,In Stock
126,Harmony Standard Series Jupiter Electric Gui...,23000000,<NA>,In Stock
127,Heritage Standard H-535 Semi-Hollow Electric...,46250000,<NA>,In Stock

## Save file yang sudah dibersihkan ke file csv baru.

In [85]:
df.to_csv('P0M1_Data_Bersih.csv', index=False)